### ISSUE TITLE
No longer needs to be built alongside packer?

### ISSUE THREAD

**Issue by OJFord** [dradtke/packer-builder-vultr#8]
The readme says:
> Due to vendoring issues, at the moment this package must be built from within Packer's source code.

But your issue hashicorp/packer#6782 was closed with resolution that once an upstream dependency's PR was merged it could be resolved, which it was in hashicorp/packer#6990.

**Comment by grahamking** [comment]
This works for me. I sent a pull request to update the install instructions to this:

- mkdir -p ~/.packer.d/plugins
- GO111MODULE=on go get github.com/dradtke/packer-builder-vultr
- mv $(go env GOBIN)/packer-builder-vultr ~/.packer.d/plugins/

Could you check if those also work for you?

**Comment by dradtke** [comment]
Closing this since I merged in the referenced PR, but feel free to reopen if something comes up.
